name: acceptance

on:
  push:
    branches:
      - "main"
      - "master"
      - "b1"
  pull_request:
    branches:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: |
          cd test/
          go test --tags=e2e
